- name: Bastion 서버에 Nginx 설치 및 설정
  hosts: bastion-node
  become: yes
  tasks:
    - name: Nginx 설치
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Nginx 설정 파일 복사
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/parcel
        mode: '0644'
      notify: Reload nginx

    - name: 심볼릭 링크 설정
      file:
        src: /etc/nginx/sites-available/parcel
        dest: /etc/nginx/sites-enabled/parcel
        state: link
        force: yes

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: restarted

# ----------------------------

- name: 프론트엔드 배포 (React 등)
  hosts: web-node
  become: yes
  tasks:
    - name: node, npm 설치
      apt:
        name: [nodejs, npm]
        state: present
        update_cache: yes

    - name: 프론트 빌드 실행
      shell: |
        cd /home/ubuntu/app/web_was/frontend
        npm install
        npm run build

    - name: 빌드 결과 /var/www 배포
      copy:
        src: /home/ubuntu/app/web_was/frontend/build/
        dest: /var/www/frontend/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

# ----------------------------

- name: 백엔드 서버 배포 및 PM2 실행
  hosts: was-node
  become: yes
  tasks:
    - name: node, npm, git 설치
      apt:
        name: [nodejs, npm, git]
        state: present
        update_cache: yes

    - name: pm2 설치
      npm:
        name: pm2
        global: yes

    - name: firebase key 복사
      copy:
        src: files/firebase-service-key.json
        dest: /home/ubuntu/app/web_was/backend/firebase-service-key.json
        mode: '0600'

    - name: 백엔드 실행
      shell: |
        cd /home/ubuntu/app/web_was/backend
        npm install
        pm2 start server.js --name backend
        pm2 save
        pm2 startup systemd
