- name: Bastion 서버에 Nginx + certbot 설치
  hosts: bastion
  become: true
  tasks:
    - name: Install nginx and certbot
      apt:
        name: [nginx, certbot, python3-certbot-nginx]
        state: present
        update_cache: yes

    - name: Copy Nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/parcel
      notify: Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/parcel
        dest: /etc/nginx/sites-enabled/parcel
        state: link
        force: yes

    - name: Get SSL certificate
      shell: certbot --nginx --non-interactive --agree-tos -m your@email.com -d {{ domain }}

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

- name: 프론트엔드 배포
  hosts: web
  become: true
  tasks:
    - name: Install nodejs, npm
      apt: name={{ item }} state=present
      loop: [nodejs, npm]

    - name: Build frontend
      shell: |
        cd /home/ubuntu/app/web_was/frontend
        npm install
        npm run build
        mkdir -p /var/www/frontend
        cp -r build/* /var/www/frontend/

- name: 백엔드 배포
  hosts: was
  become: true
  tasks:
    - name: Install nodejs, npm, pm2
      apt: name={{ item }} state=present
      loop: [nodejs, npm]
    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Deploy and run
      shell: |
        cd /home/ubuntu/app/web_was/backend
        npm install
        pm2 start server.js --name backend
        pm2 save
